

STOCK_DATA = {
    # Technology
    "AAPL": {"name": "Apple Inc.", "sector": "Technology"},
    "MSFT": {"name": "Microsoft Corporation", "sector": "Technology"},
    "GOOGL": {"name": "Alphabet Inc. (Google)", "sector": "Technology"},
    "AMZN": {"name": "Amazon.com Inc.", "sector": "Technology"},
    "TSLA": {"name": "Tesla Inc.", "sector": "Technology"},
    "NVDA": {"name": "NVIDIA Corporation", "sector": "Technology"},
    "META": {"name": "Meta Platforms Inc.", "sector": "Technology"},
    "NFLX": {"name": "Netflix Inc.", "sector": "Technology"},
    "ORCL": {"name": "Oracle Corporation", "sector": "Technology"},
    "CRM": {"name": "Salesforce Inc.", "sector": "Technology"},
    "ADBE": {"name": "Adobe Inc.", "sector": "Technology"},
    "INTC": {"name": "Intel Corporation", "sector": "Technology"},
    "AMD": {"name": "Advanced Micro Devices", "sector": "Technology"},
    "IBM": {"name": "IBM Corporation", "sector": "Technology"},
    "QCOM": {"name": "Qualcomm Inc.", "sector": "Technology"},
    "AVGO": {"name": "Broadcom Inc.", "sector": "Technology"},
    "TXN": {"name": "Texas Instruments", "sector": "Technology"},
    "AMAT": {"name": "Applied Materials Inc.", "sector": "Technology"},
    "MU": {"name": "Micron Technology", "sector": "Technology"},
    "LRCX": {"name": "Lam Research Corporation", "sector": "Technology"},

    # Finance
    "JPM": {"name": "JPMorgan Chase & Co.", "sector": "Finance"},
    "BAC": {"name": "Bank of America Corp.", "sector": "Finance"},
    "WFC": {"name": "Wells Fargo & Company", "sector": "Finance"},
    "GS": {"name": "Goldman Sachs Group Inc.", "sector": "Finance"},
    "MS": {"name": "Morgan Stanley", "sector": "Finance"},
    "C": {"name": "Citigroup Inc.", "sector": "Finance"},
    "BLK": {"name": "BlackRock Inc.", "sector": "Finance"},
    "AXP": {"name": "American Express Company", "sector": "Finance"},
    "USB": {"name": "U.S. Bancorp", "sector": "Finance"},
    "PNC": {"name": "PNC Financial Services", "sector": "Finance"},
    "TFC": {"name": "Truist Financial Corporation", "sector": "Finance"},
    "COF": {"name": "Capital One Financial Corp.", "sector": "Finance"},
    "SCHW": {"name": "Charles Schwab Corporation", "sector": "Finance"},
    "BK": {"name": "Bank of New York Mellon", "sector": "Finance"},
    "SPGI": {"name": "S&P Global Inc.", "sector": "Finance"},
    "MCO": {"name": "Moody's Corporation", "sector": "Finance"},
    "ICE": {"name": "Intercontinental Exchange", "sector": "Finance"},
    "CME": {"name": "CME Group Inc.", "sector": "Finance"},
    "AON": {"name": "Aon plc", "sector": "Finance"},
    "MET": {"name": "MetLife Inc.", "sector": "Finance"},

    # Healthcare
    "JNJ": {"name": "Johnson & Johnson", "sector": "Healthcare"},
    "PFE": {"name": "Pfizer Inc.", "sector": "Healthcare"},
    "UNH": {"name": "UnitedHealth Group Inc.", "sector": "Healthcare"},
    "ABBV": {"name": "AbbVie Inc.", "sector": "Healthcare"},
    "TMO": {"name": "Thermo Fisher Scientific", "sector": "Healthcare"},
    "MDT": {"name": "Medtronic plc", "sector": "Healthcare"},
    "ABT": {"name": "Abbott Laboratories", "sector": "Healthcare"},
    "DHR": {"name": "Danaher Corporation", "sector": "Healthcare"},
    "CVS": {"name": "CVS Health Corporation", "sector": "Healthcare"},
    "AMGN": {"name": "Amgen Inc.", "sector": "Healthcare"},
    "GILD": {"name": "Gilead Sciences Inc.", "sector": "Healthcare"},
    "BIIB": {"name": "Biogen Inc.", "sector": "Healthcare"},
    "VRTX": {"name": "Vertex Pharmaceuticals", "sector": "Healthcare"},
    "REGN": {"name": "Regeneron Pharmaceuticals", "sector": "Healthcare"},
    "ISRG": {"name": "Intuitive Surgical Inc.", "sector": "Healthcare"},
    "ZTS": {"name": "Zoetis Inc.", "sector": "Healthcare"},
    "HUM": {"name": "Humana Inc.", "sector": "Healthcare"},
    "CI": {"name": "Cigna Corporation", "sector": "Healthcare"},
    "EW": {"name": "Edwards Lifesciences Corp.", "sector": "Healthcare"},
    "BSX": {"name": "Boston Scientific Corporation", "sector": "Healthcare"},

    # Consumer
    "PG": {"name": "Procter & Gamble Co.", "sector": "Consumer"},
    "KO": {"name": "Coca-Cola Company", "sector": "Consumer"},
    "PEP": {"name": "PepsiCo Inc.", "sector": "Consumer"},
    "WMT": {"name": "Walmart Inc.", "sector": "Consumer"},
    "HD": {"name": "Home Depot Inc.", "sector": "Consumer"},
    "MCD": {"name": "McDonald's Corporation", "sector": "Consumer"},
    "NKE": {"name": "Nike Inc.", "sector": "Consumer"},
    "SBUX": {"name": "Starbucks Corporation", "sector": "Consumer"},
    "UL": {"name": "Unilever PLC", "sector": "Consumer"},
    "CL": {"name": "Colgate-Palmolive Company", "sector": "Consumer"},
    "CHD": {"name": "Church & Dwight Co.", "sector": "Consumer"},
    "KMB": {"name": "Kimberly-Clark Corporation", "sector": "Consumer"},
    "SJM": {"name": "J.M. Smucker Company", "sector": "Consumer"},
    "GIS": {"name": "General Mills Inc.", "sector": "Consumer"},
    "K": {"name": "Kellogg Company", "sector": "Consumer"},
    "MDLZ": {"name": "Mondelez International", "sector": "Consumer"},
    "TSN": {"name": "Tyson Foods Inc.", "sector": "Consumer"},
    "HRL": {"name": "Hormel Foods Corporation", "sector": "Consumer"},
    "CAG": {"name": "Conagra Brands Inc.", "sector": "Consumer"},
    "CPB": {"name": "Campbell Soup Company", "sector": "Consumer"},

    # Industrial
    "CAT": {"name": "Caterpillar Inc.", "sector": "Industrial"},
    "GE": {"name": "General Electric Company", "sector": "Industrial"},
    "MMM": {"name": "3M Company", "sector": "Industrial"},
    "HON": {"name": "Honeywell International Inc.", "sector": "Industrial"},
    "RTX": {"name": "RTX Corporation", "sector": "Industrial"},
    "LMT": {"name": "Lockheed Martin Corporation", "sector": "Industrial"},
    "BA": {"name": "Boeing Company", "sector": "Industrial"},
    "UNP": {"name": "Union Pacific Corporation", "sector": "Industrial"},
    "NSC": {"name": "Norfolk Southern Corporation", "sector": "Industrial"},
    "CSX": {"name": "CSX Corporation", "sector": "Industrial"},
    "FDX": {"name": "FedEx Corporation", "sector": "Industrial"},
    "UPS": {"name": "United Parcel Service Inc.", "sector": "Industrial"},
    "DE": {"name": "Deere & Company", "sector": "Industrial"},
    "ITW": {"name": "Illinois Tool Works Inc.", "sector": "Industrial"},
    "EMR": {"name": "Emerson Electric Co.", "sector": "Industrial"},
    "PH": {"name": "Parker-Hannifin Corporation", "sector": "Industrial"},
    "ROK": {"name": "Rockwell Automation Inc.", "sector": "Industrial"},
    "ETN": {"name": "Eaton Corporation plc", "sector": "Industrial"},
    "DOV": {"name": "Dover Corporation", "sector": "Industrial"},
    "OTIS": {"name": "Otis Worldwide Corporation", "sector": "Industrial"},

    # Energy
    "XOM": {"name": "Exxon Mobil Corporation", "sector": "Energy"},
    "CVX": {"name": "Chevron Corporation", "sector": "Energy"},
    "COP": {"name": "ConocoPhillips", "sector": "Energy"},
    "EOG": {"name": "EOG Resources Inc.", "sector": "Energy"},
    "SLB": {"name": "Schlumberger Limited", "sector": "Energy"},
    "BKR": {"name": "Baker Hughes Company", "sector": "Energy"},
    "HAL": {"name": "Halliburton Company", "sector": "Energy"},
    "PSX": {"name": "Phillips 66", "sector": "Energy"},
    "VLO": {"name": "Valero Energy Corporation", "sector": "Energy"},
    "MPC": {"name": "Marathon Petroleum Corporation", "sector": "Energy"},
    "HFC": {"name": "HollyFrontier Corporation", "sector": "Energy"},
    "WMB": {"name": "Williams Companies Inc.", "sector": "Energy"},
    "OKE": {"name": "ONEOK Inc.", "sector": "Energy"},
    "KMI": {"name": "Kinder Morgan Inc.", "sector": "Energy"},
    "WES": {"name": "Western Midstream Partners LP", "sector": "Energy"},
    "EPD": {"name": "Enterprise Products Partners L.P.", "sector": "Energy"},
    "ET": {"name": "Energy Transfer LP", "sector": "Energy"},
    "MPLX": {"name": "MPLX LP", "sector": "Energy"},
    "PAA": {"name": "Plains All American Pipeline LP", "sector": "Energy"},
    "DUK": {"name": "Duke Energy Corporation", "sector": "Energy"},

    # Utilities
    "NEE": {"name": "NextEra Energy Inc.", "sector": "Utilities"},
    "SO": {"name": "Southern Company", "sector": "Utilities"},
    "D": {"name": "Dominion Energy Inc.", "sector": "Utilities"},
    "AEP": {"name": "American Electric Power Company", "sector": "Utilities"},
    "EXC": {"name": "Exelon Corporation", "sector": "Utilities"},
    "SRE": {"name": "Sempra Energy", "sector": "Utilities"},
    "XEL": {"name": "Xcel Energy Inc.", "sector": "Utilities"},
    "PEG": {"name": "Public Service Enterprise Group", "sector": "Utilities"},
    "ED": {"name": "Consolidated Edison Inc.", "sector": "Utilities"},
    "WEC": {"name": "WEC Energy Group Inc.", "sector": "Utilities"},
    "DTE": {"name": "DTE Energy Company", "sector": "Utilities"},
    "ES": {"name": "Eversource Energy", "sector": "Utilities"},
    "ETR": {"name": "Entergy Corporation", "sector": "Utilities"},
    "FE": {"name": "FirstEnergy Corp.", "sector": "Utilities"},
    "AES": {"name": "AES Corporation", "sector": "Utilities"},
    "LNT": {"name": "Alliant Energy Corporation", "sector": "Utilities"},
    "CMS": {"name": "CMS Energy Corporation", "sector": "Utilities"},
    "CNP": {"name": "CenterPoint Energy Inc.", "sector": "Utilities"},
    "NI": {"name": "NiSource Inc.", "sector": "Utilities"},
    "ATO": {"name": "Atmos Energy Corporation", "sector": "Utilities"}
}


TIMEFRAME_MAP = {
    '1d':  {'alpaca': '1Day',  'days': 1},
    '1wk': {'alpaca': '1Day',  'days': 7},
    '1mo': {'alpaca': '1Day',  'days': 30},
    '3mo': {'alpaca': '1Day',  'days': 90},
    '1y':  {'alpaca': '1Day',  'days': 365},
    'max': {'alpaca': '1Week', 'days': 1825}
}